### ISSUE TITLE
 Protobuf check failing for is_deleted key

### ISSUE THREAD

**Issue by jigarjain** [ramnique/see-js#2]
I discovered that on response of `allocate` call, the protobuf check was failing due to a key `is_deleted` which was set on `Variation` object from API response. But the same key was not part of protobuf definition.

On further digging, I found that `is_deleted` is required to be part of protobuf definition for both `Experiment` & `Variation` model.

**Comment by jigarjain** [comment]
Please find the PR here for the same @ #1

**Comment by ramnique** [comment]
fixed in 1.4.1
